(() => {
  pageMeta.facebook=['FACEBOOK PAGE','Auto Post เพจ Facebook'];
  const page=document.createElement('section');page.className='page fb-studio';page.dataset.view='facebook';
  page.innerHTML=`<section class="page-intro"><span class="eyebrow">FACEBOOK • CONTENT PLANNER</span><h1>คลิปพร้อมแล้ว วางแผนโพสต์ต่อได้เลย</h1><p>เลือกคลิป → จัดเวลา → ตรวจแผน → ส่งให้ Facebook ตั้งเวลา • ไม่โพสต์เองระหว่างสร้างคลิป</p></section>
  <section class="panel fb-connection"><div><span class="eyebrow">เพจปลายทาง</span><h2 id="fb-page">ยังไม่ได้เชื่อมต่อ</h2><small>เวลาทั้งหมดเป็นเวลาไทย Asia/Bangkok</small></div><details><summary>เชื่อมต่อ / เปลี่ยนเพจ</summary><label>Page Access Token<input id="fb-token" type="password" autocomplete="new-password" placeholder="วาง Token ของเพจ"></label><div class="fb-actions"><button class="button primary" id="fb-connect">ตรวจสอบและบันทึก</button><button class="button ghost" id="fb-disconnect">ยกเลิกการเชื่อมต่อ</button></div><small>เก็บใน Windows Credential Manager • ไม่ส่ง Token ให้ Extension</small></details></section>
  <p id="fb-status" class="fb-notice" role="status" aria-live="polite">เพิ่มคลิปและบันทึกแผนได้โดยยังไม่ส่งโพสต์</p>
  <div class="fb-layout"><section class="panel fb-library"><div class="fb-heading"><h2>1. เลือกจากคลังคลิป</h2><button class="button ghost" id="fb-refresh">รีเฟรช</button></div>
  <label>หมวดหมู่<select id="fb-category"><option value="all">ทั้งหมด</option><option value="product">ทำคลิปสินค้า Shopee</option><option value="story">เรื่องเล่า Shorts</option><option value="drama">ละครสั้น AI</option><option value="long">คลิปยาว</option></select></label><label>ค้นหาคลิป<input id="fb-search" type="search" placeholder="ชื่อคลิป หรือชื่องาน"></label><label>สถานะของเพจที่เลือก<select id="fb-filter"><option value="all">ทั้งหมด</option><option value="new">ยังไม่เคยส่ง</option><option value="scheduled">ตั้งเวลาแล้ว</option><option value="published">เผยแพร่แล้ว</option></select></label>
  <div class="fb-actions"><button class="button ghost" id="fb-select-visible">ติ๊กผลค้นหาทั้งหมด</button><button class="button ghost" id="fb-unselect">เลิกเลือก</button></div><div class="fb-actions"><label class="fb-inline">สุ่ม <input id="fb-random-count" type="number" min="1" max="200" value="3" aria-label="จำนวนคลิปที่สุ่ม"> คลิป</label><button class="button ghost" id="fb-random">สุ่มจากผลค้นหา</button></div><p id="fb-selection"></p><div id="fb-clips" class="fb-clips"></div><button class="button primary fb-add" id="fb-add">+ เพิ่มคลิปที่ติ๊กเข้า Planner</button><small>เฉพาะ Final ที่บันทึกแล้ว • ไม่สร้างคลิปใหม่</small></section>
  <section class="panel fb-planner"><div class="fb-heading"><div><h2>2. จัดตารางโพสต์</h2><small id="fb-summary"></small></div><button class="button ghost" id="fb-check-drafts">ติ๊กแบบร่างทั้งหมด</button></div>
  <div class="fb-time-tools"><label>วัน–เวลาเริ่มต้น (ไทย)<input id="fb-start" type="datetime-local"></label><label>เว้นแต่ละคลิป<input id="fb-interval" type="number" min="1" value="1"></label><label>หน่วย<select id="fb-unit"><option value="1440">วัน</option><option value="60">ชั่วโมง</option><option value="1">นาที</option></select></label><button class="button ghost" id="fb-spread">ดูแผนไล่เวลา</button></div>
  <div class="fb-actions fb-shifts"><span>บวกเวลาแถวที่ติ๊ก</span><button class="button ghost" data-shift="15">+15 นาที</button><button class="button ghost" data-shift="30">+30 นาที</button><button class="button ghost" data-shift="60">+1 ชม.</button><button class="button ghost" data-shift="1440">+1 วัน</button><label class="fb-inline"><input id="fb-shift-minutes" type="number" min="1" value="60" aria-label="บวกเวลากี่นาที"> นาที</label><button class="button ghost" id="fb-shift-custom">ดูแผนบวกเวลา</button></div><small>แก้ได้เฉพาะแบบร่าง • เผื่ออัปโหลดอย่างน้อย 20 นาที ไม่เกิน 180 วัน • ไม่เปลี่ยนเวลาให้อัตโนมัติ</small>
  <div class="fb-table-scroll"><table class="fb-table"><thead><tr><th>เลือก</th><th>คลิป / ข้อความโพสต์</th><th>วัน–เวลาไทย / สถานะ</th><th>จัดการ</th></tr></thead><tbody id="fb-rows"></tbody></table></div><div class="fb-actions"><button class="button ghost" id="fb-save">บันทึกแบบร่าง</button><button class="button ghost" id="fb-remove">ลบแถวที่ติ๊ก</button></div>
  <div class="fb-send-bar"><button class="button primary" id="fb-schedule">ส่งตารางที่ติ๊กให้ Facebook</button><button class="button ghost" id="fb-now">โพสต์ที่ติ๊กทันที</button><button class="button ghost" id="fb-pause">พักการส่งชุดนี้</button></div><p id="fb-batch" role="status"></p><small>ต้องเปิดโปรแกรมระหว่างอัปโหลด • เมื่อขึ้น “ตั้งเวลาแล้ว” Facebook จะโพสต์ให้แม้ปิดโปรแกรม<br>ปุ่มพักหยุดรายการถัดไป ไม่ยกเลิกตารางที่ Facebook รับไปแล้ว • ปุ่มลบลบเฉพาะแบบร่าง ไม่ลบไฟล์คลิป</small></section></div>
  <section class="panel fb-history"><h2>ประวัติและหลักฐานจาก Facebook</h2><p>หากต้องแก้ / ยกเลิกตารางที่ส่งแล้ว ให้จัดการในเพจ รายการไม่ชัดเจนจะไม่ถูกส่งซ้ำ</p><div id="fb-history"></div></section>
  <dialog id="fb-preview"><div class="fb-heading"><h2>ดูคลิปก่อนโพสต์</h2><button class="button ghost" id="fb-close-preview">ปิด</button></div><video controls preload="metadata"></video></dialog>`;
  document.querySelector('[data-view="settings"]').after(page);
  const q=s=>page.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={draft:'แบบร่าง',queued:'รอส่ง',submitted:'ส่งแล้ว',uploading:'กำลังอัปโหลด',processing:'Facebook กำลังประมวลผล',scheduled:'ตั้งเวลาแล้ว',published:'เผยแพร่แล้ว',review:'ต้องตรวจผลเดิมก่อน'};
  let saved={planner:{rows:[],revision:0,batch:{}},posts:[]},busy=false,polling=false,dirty=false;
  const clips=new Set(),selected=new Set(),edited=new Set(),notice=t=>q('#fb-status').textContent=t;
  const local=t=>t?new Date(t*1000+7*3600000).toISOString().slice(0,16):'';
  const editable=r=>r.status==='draft'&&!r.post_id,currentRows=()=>saved.planner.rows.filter(r=>r.page_id===saved.page?.id);
  async function call(action,payload={}){const r=await fetch('/api/desktop/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'ทำรายการไม่ได้');return d;}
  function accept(d){saved=d;edited.clear();render();}
  async function refresh(){const d=await call('facebook_status');if(!dirty)accept(d);}
  function library(){const term=q('#fb-search').value.trim().toLocaleLowerCase(),kind=q('#fb-category').value,filter=q('#fb-filter').value;return (ui.state?.library||[]).filter(item=>{const category=item.content_kind==='product'?'product':item.content_kind==='drama'?'drama':item.aspect_ratio==='16:9'?'long':'story';const posts=saved.posts.filter(p=>p.item_id===item.item_id&&p.page_id===saved.page?.id);return (kind==='all'||kind===category)&&(!term||`${item.title} ${item.item_id}`.toLocaleLowerCase().includes(term))&&(filter==='all'||(filter==='new'?!posts.length:posts.some(p=>p.status===filter)));});}
  const media=(item,kind)=>'/api/desktop/media?item_id='+encodeURIComponent(item)+'&kind='+kind;
  function renderClips(){const list=library();q('#fb-selection').textContent=`พบ ${list.length} คลิป • ติ๊กไว้ ${clips.size} คลิป (รวมที่อยู่นอกผลค้นหา)`;q('#fb-clips').innerHTML=list.length?list.map(item=>`<article class="fb-clip"><input type="checkbox" data-clip="${esc(item.item_id)}" aria-label="เลือก ${esc(item.title)}" ${clips.has(item.item_id)?'checked':''}><img loading="lazy" src="${esc(media(item.item_id,item.cover_url?'cover':'preview'))}" alt=""><div><strong>${esc(item.title)}</strong><small>${esc(item.kind_label||'Final')} • ${Math.round(item.duration_seconds||0)} วินาที</small><button class="button ghost" data-preview="${esc(item.item_id)}">ดูคลิป</button></div></article>`).join(''):'<p class="fb-empty">ไม่มีคลิปตรงกับตัวกรองนี้</p>';}
  function render(){
    q('#fb-page').textContent=saved.page?`${saved.page.name} • ${saved.page.id}`:'ยังไม่ได้เชื่อมต่อ';if(!saved.page)page.querySelector('.fb-connection details').open=true;renderClips();const rows=currentRows();
    for(const id of selected)if(!rows.some(r=>r.id===id&&editable(r)))selected.delete(id);
    q('#fb-summary').textContent=`${rows.length} รายการ • แบบร่าง ${rows.filter(editable).length} • ตั้งเวลาแล้ว ${rows.filter(r=>r.status==='scheduled').length} • เผยแพร่แล้ว ${rows.filter(r=>r.status==='published').length}`;
    q('#fb-rows').innerHTML=rows.length?rows.map((r,i)=>`<tr data-row="${esc(r.id)}"><td><input type="checkbox" data-row-check="${esc(r.id)}" aria-label="เลือกแถว ${i+1}" ${selected.has(r.id)?'checked':''} ${editable(r)?'':'disabled'}><small>${i+1}</small></td><td><div class="fb-row-title"><img loading="lazy" src="${esc(media(r.item_id,'preview'))}" alt=""><strong>${esc(r.title)}</strong></div><textarea data-caption rows="3" maxlength="5000" aria-label="ข้อความโพสต์ ${i+1}" ${editable(r)?'':'disabled'}>${esc(r.caption)}</textarea></td><td><input data-time type="datetime-local" value="${local(r.scheduled_at)}" aria-label="เวลาแถว ${i+1}" ${editable(r)?'':'disabled'}><span class="fb-badge fb-${esc(r.status)}">${esc(labels[r.status]||r.status)}</span><small>${esc(r.message||'')}</small></td><td><div class="fb-row-actions"><button class="button ghost" data-move="-1" ${editable(r)?'':'disabled'} aria-label="เลื่อนแถว ${i+1} ขึ้น">↑</button><button class="button ghost" data-move="1" ${editable(r)?'':'disabled'} aria-label="เลื่อนแถว ${i+1} ลง">↓</button><button class="button ghost" data-preview="${esc(r.item_id)}">ดูคลิป</button></div></td></tr>`).join(''):'<tr><td colspan="4" class="fb-empty">ติ๊กคลิปด้านซ้าย แล้วกด “เพิ่มเข้า Planner”</td></tr>';
    const batch=saved.planner.batch||{};q('#fb-batch').textContent=batch.active?(batch.paused?'กำลังพัก • รอรายการที่เริ่มอัปโหลดแล้วจบ':'กำลังส่งทีละรายการ • ดูสถานะแต่ละแถว'):'ไม่มีชุดกำลังส่ง • รายการประมวลผล / ตั้งเวลาแล้ว ตรวจผลต่อได้';
    q('#fb-history').replaceChildren();for(const row of saved.posts.filter(r=>r.page_id===saved.page?.id)){const el=document.createElement('div');el.className='fb-history-row';const title=document.createElement('strong');title.textContent=`${row.title} • ${labels[row.status]||row.status}`;el.append(title);const info=document.createElement('small');info.textContent=`${row.message||''} ${row.video_id?'• ID '+row.video_id:''}${row.remote_scheduled_at?' • เวลา Facebook '+local(row.remote_scheduled_at).replace('T',' '):''}`;el.append(info);if(row.video_id){const b=document.createElement('button');b.className='button ghost';b.textContent='ตรวจผลเดิม';b.onclick=()=>run(async()=>{await call('facebook_check',{id:row.id});await refresh();});el.append(b);}if(/^https:\/\/(www\.)?facebook\.com\//.test(row.url||'')){const a=document.createElement('a');a.href=row.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='เปิดใน Facebook';el.append(a);}q('#fb-history').append(el);}
  }
  async function run(fn){if(busy)return;busy=true;page.setAttribute('aria-busy','true');const controls=[...page.querySelectorAll('button,input,select,textarea')].map(el=>[el,el.disabled]);controls.forEach(([el])=>el.disabled=true);try{await fn();}catch(e){notice(e.message);}finally{controls.forEach(([el,disabled])=>{if(el.isConnected)el.disabled=disabled;});busy=false;page.removeAttribute('aria-busy');}}
  function ids(){const values=currentRows().filter(r=>selected.has(r.id)&&editable(r)).map(r=>r.id);if(!values.length)throw Error('ติ๊กแบบร่างที่ต้องการก่อน');return values;}
  async function save(){if(!dirty)return;const updates={};for(const row of currentRows().filter(r=>editable(r)&&edited.has(r.id))){const el=q(`[data-row="${row.id}"]`);updates[row.id]={caption:el.querySelector('[data-caption]').value,time:el.querySelector('[data-time]').value};}const d=await call('facebook_planner_edit',{operation:'save',ids:Object.keys(updates),updates,revision:saved.planner.revision});dirty=false;accept(d);}
  async function edit(operation,extra={}){await save();accept(await call('facebook_planner_edit',{operation,ids:ids(),revision:saved.planner.revision,...extra}));}
  async function times(operation,extra){await save();const payload={operation,ids:ids(),revision:saved.planner.revision,...extra};const d=await call('facebook_planner_edit',{...payload,preview:true});if(!confirm('ตรวจแผนเวลาไทยก่อนใช้\n'+d.preview.map(r=>`${r.time.replace('T',' ')} • ${r.title}`).join('\n')+'\n\nใช้เวลานี้กับเฉพาะแถวที่ติ๊ก? ยังไม่ส่งไป Facebook'))return;accept(await call('facebook_planner_edit',payload));notice('บันทึกเวลาแล้ว • ยังไม่ส่งโพสต์');}
  q('#fb-connect').onclick=()=>run(async()=>{if(dirty)throw Error('บันทึกแบบร่างก่อนเปลี่ยนเพจ');const token=q('#fb-token').value;q('#fb-token').value='';accept(await call('facebook_connect',{token}));notice('เชื่อมต่อเพจแล้ว');});
  q('#fb-disconnect').onclick=()=>run(async()=>{if(dirty)await save();accept(await call('facebook_disconnect'));});
  q('#fb-refresh').onclick=()=>run(async()=>{if(dirty&&!confirm('ทิ้งข้อความ / เวลาที่ยังไม่ได้บันทึก แล้วโหลดแผนล่าสุด?'))return;dirty=false;await refresh();notice('โหลดข้อมูลล่าสุดแล้ว');});
  for(const name of ['#fb-category','#fb-filter','#fb-search'])q(name).addEventListener('input',renderClips);
  q('#fb-select-visible').onclick=()=>{library().forEach(i=>clips.add(i.item_id));renderClips();};q('#fb-unselect').onclick=()=>{clips.clear();renderClips();};
  q('#fb-random').onclick=()=>{const n=Number(q('#fb-random-count').value),items=library();if(!Number.isInteger(n)||n<1||n>Math.min(200,items.length)){notice('จำนวนสุ่มต้องไม่เกินคลิปในผลค้นหา และไม่เกิน 200');return;}for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}clips.clear();items.slice(0,n).forEach(i=>clips.add(i.item_id));renderClips();};
  q('#fb-add').onclick=()=>run(async()=>{await save();accept(await call('facebook_planner_add',{ids:[...clips],revision:saved.planner.revision}));clips.clear();renderClips();notice('เพิ่มเข้าแผนแล้ว • คลิปซ้ำในเพจเดิมจะไม่เพิ่มซ้ำ');});
  q('#fb-check-drafts').onclick=()=>{const rows=currentRows().filter(editable),all=rows.every(r=>selected.has(r.id));rows.forEach(r=>all?selected.delete(r.id):selected.add(r.id));q('#fb-rows').querySelectorAll('[data-row-check]').forEach(e=>e.checked=selected.has(e.dataset.rowCheck));};
  q('#fb-save').onclick=()=>run(async()=>{await save();notice('บันทึกแบบร่างแล้ว • ยังไม่ส่งโพสต์');});q('#fb-remove').onclick=()=>run(async()=>{ids();if(confirm('ลบเฉพาะแถวแบบร่างที่ติ๊ก? ไฟล์คลิปและประวัติโพสต์จะยังอยู่')){await edit('remove');notice('ลบแบบร่างที่เลือกแล้ว • ไฟล์คลิปยังอยู่');}});
  q('#fb-spread').onclick=()=>run(()=>times('spread',{start:q('#fb-start').value,minutes:Number(q('#fb-interval').value)*Number(q('#fb-unit').value)}));q('#fb-shift-custom').onclick=()=>run(()=>times('shift',{minutes:Number(q('#fb-shift-minutes').value)}));page.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>run(()=>times('shift',{minutes:Number(b.dataset.shift)})));
  async function send(mode){await save();const chosen=ids();if(!saved.page)throw Error('เชื่อมต่อเพจก่อน');if(!confirm(`${mode==='schedule'?'ส่งตารางให้ Facebook ตั้งเวลา':'เผยแพร่ทันที'} ${chosen.length} คลิป\nเพจ ${saved.page.name} (${saved.page.id})\n${mode==='schedule'?'เวลาไทยตามแถวที่ติ๊ก':'คลิปจะเริ่มเผยแพร่เมื่อประมวลผลเสร็จ'}\nยืนยันส่งจริง?`))return;accept(await call('facebook_planner_start',{ids:chosen,revision:saved.planner.revision,page_id:saved.page.id,mode}));notice('รับชุดโพสต์แล้ว • รอตรวจสถานะจาก Facebook ไม่ถือว่าเผยแพร่สำเร็จทันที');}
  q('#fb-schedule').onclick=()=>run(()=>send('schedule'));q('#fb-now').onclick=()=>run(()=>send('now'));q('#fb-pause').onclick=()=>run(async()=>{await call('facebook_planner_pause');await refresh();notice('พักรายการถัดไปแล้ว • ตารางที่ Facebook รับแล้วยังคงอยู่');});
  page.addEventListener('change',e=>{if(e.target.dataset.clip){e.target.checked?clips.add(e.target.dataset.clip):clips.delete(e.target.dataset.clip);q('#fb-selection').textContent=`ติ๊กไว้ ${clips.size} คลิป`;}if(e.target.dataset.rowCheck){e.target.checked?selected.add(e.target.dataset.rowCheck):selected.delete(e.target.dataset.rowCheck);}});q('#fb-rows').addEventListener('input',e=>{if(e.target.matches('[data-caption],[data-time]')){dirty=true;edited.add(e.target.closest('[data-row]').dataset.row);notice('มีการแก้ไขที่ยังไม่บันทึก');}});
  page.addEventListener('click',e=>{const preview=e.target.closest('[data-preview]');if(preview){q('#fb-preview video').src=media(preview.dataset.preview,'video');q('#fb-preview').showModal();}const move=e.target.closest('[data-move]');if(move)run(async()=>{const id=move.closest('[data-row]').dataset.row;await save();accept(await call('facebook_planner_edit',{operation:'move',ids:[id],direction:Number(move.dataset.move),revision:saved.planner.revision}));});});
  q('#fb-close-preview').onclick=()=>q('#fb-preview').close();q('#fb-preview').addEventListener('close',()=>{const video=q('#fb-preview video');video.pause();video.removeAttribute('src');video.load();});
  document.querySelector('[data-page="facebook"]').addEventListener('click',()=>run(refresh));q('#fb-start').value=local(Date.now()/1000+3600);
  // Read one remote receipt per tick. A timer can NEVER create a post or erase an edited draft.
  setInterval(async()=>{if(busy||polling||dirty||document.hidden||!page.classList.contains('active'))return;polling=true;try{const pending=saved.posts.filter(r=>r.page_id===saved.page?.id&&r.video_id&&(r.status==='processing'||(r.status==='scheduled'&&r.scheduled_at<=Date.now()/1000+60))).sort((a,b)=>(a.checked_at||0)-(b.checked_at||0));if(pending.length)await call('facebook_check',{id:pending[0].id});await refresh();}catch(e){notice('ตรวจสถานะยังไม่ได้ • เก็บรายการเดิมไว้: '+e.message);}finally{polling=false;}},15000);
  if(location.hash==='#facebook'){showPage('facebook');run(refresh);}
})();
