const fs = require('fs'), vm = require('vm'), assert = require('assert');
const source = fs.readFileSync('browser_extension/chatgpt.js', 'utf8');
const start = source.indexOf('  function speechDeliveryRepairInstruction(');
const end = source.indexOf('\n  function ', start + 10);
const ctx = {}; vm.createContext(ctx); vm.runInContext(source.slice(start, end), ctx);
assert.equal(ctx.speechDeliveryRepairInstruction({request:{}}), '');
assert.throws(()=>ctx.speechDeliveryRepairInstruction({request:{speech_delivery_version:1}}), /SPEECH_DELIVERY_REVIEW/);
const instruction = 'SPEECH DELIVERY v1:\nPreserve facts and exact speech.\nEND SPEECH DELIVERY v1';
const result = ctx.speechDeliveryRepairInstruction({request:{speech_delivery_version:1,speech_delivery_instruction:instruction}});
assert(result.startsWith(instruction)); assert(result.includes('preserve approved spoken words'));
assert(result.includes('outside speech fields'));
assert(source.includes('creativeStyle,speechDeliveryRepairInstruction(pkg)'));
assert(source.includes('Write VISUAL MOTION ONLY in prompt'));
console.log('speech delivery extension fixtures passed');
const speakerStart = source.indexOf('  function validateSpeechSpeakers(');
const speakerEnd = source.indexOf('\n  function ', speakerStart + 10);
vm.runInContext(source.slice(speakerStart, speakerEnd), ctx);
ctx.validateSpeechSpeakers({dialogue_turns:[{speaker:'พ่อ',text:'สวัสดีจ้า'}]}, ['พ่อ']);
assert.throws(()=>ctx.validateSpeechSpeakers({dialogue_turns:[{speaker:'แม่',text:'สวัสดี'}]}, ['พ่อ']), /SPEECH_DELIVERY_REVIEW/);
