const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../web_ui/studio.js'), 'utf8');
const start = source.indexOf('  function storyContentMarkup(');
const end = source.indexOf('  function paintReview(', start);
assert.ok(start >= 0 && end > start);
const context = vm.createContext({escapeHtml:value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))});
// The extracted renderer reads the same review state owned by the real modal.
context.studio = {review: null};
vm.runInContext(source.slice(start,end),context);
const render=review=>context.storyContentMarkup(review);
assert.match(render({}),/งานเดิม/);
assert.match(render({content_review:{status:'pending'}}),/รอแผนภาพ/);
const markup=render({content_review:{status:'needs_review',entities:[{id:'doom',name:'Doctor Doom',visual_identity:'silver mask'}],issues:[{scene:1,code:'entity_missing',message:'ไม่พบ Doctor Doom'}]}});
assert.match(markup,/Doctor Doom/);
assert.match(markup,/ฉาก 1/);
assert.match(markup,/needs-review/);
assert.match(markup,/ไม่ใช่การยืนยันว่าภาพ AI ตรงทั้งหมด/);
assert.doesNotMatch(markup,/<button|data-action|fetch\(/);
const escaped=render({content_review:{status:'<script>',entities:[{name:'<img onerror="bad()">',visual_identity:'<script>bad()</script>'}],issues:[{scene:'<b>',message:'<svg onload="bad()">'}]}});
assert.doesNotMatch(escaped,/<script|<img|<svg|class="studio-content-review <script>/);
assert.match(escaped,/&lt;img/);
const ready=render({content_review:{status:'ready',entities:[],issues:[]}});
assert.match(ready,/ตรวจชื่อและโครงสร้างแผนภาพแล้ว/);
assert.match(ready,/ไม่ถูกแก้หรือสร้างทับ/);
assert.ok(source.includes('${storyContentMarkup(review)}'));
const cast=context.storySceneIdentityMarkup({content_review:{entities:[{id:'doom',name:'Doctor Doom'},{id:'loki',name:'Loki'}],scene_entities:[['doom'],['loki']]}},{index:1});
assert.match(cast,/Doctor Doom/);
assert.doesNotMatch(cast,/Loki/);
assert.equal(context.storySceneIdentityMarkup({},{index:1}),'');
const editable=context.storyScenePromptMarkup({index:1,prompt:'</textarea><script>bad()</script>',prompt_editable:true,prompt_revised:true});
assert.match(editable,/data-save-scene="1"/);
assert.match(editable,/ไม่สร้างอัตโนมัติ/);
assert.match(editable,/&lt;\/textarea&gt;/);
assert.doesNotMatch(editable,/<script>/);
assert.doesNotMatch(context.storyScenePromptMarkup({index:2,prompt:'complete',prompt_editable:false}),/<textarea|data-save-scene/);
assert.equal(context.storyScenePromptMarkup({index:'<img>'}),'');
context.studio.review = {video_plan: {supported: true}};
const planned = context.storyScenePromptMarkup({index:3, flow_editable:true,
  flow_prompt:'</textarea><script>bad()</script>', flow_model:'\" onfocus=\"bad()'});
assert.match(planned,/data-save-flow="3"/);
assert.match(planned,/type="hidden" data-flow-model="3"/);
assert.match(planned,/&lt;\/textarea&gt;/);
assert.match(planned,/&quot; onfocus=&quot;bad\(\)/);
assert.doesNotMatch(planned,/<script>|<select|value="" onfocus=/);
assert.doesNotMatch(context.storyScenePromptMarkup({index:4, flow_editable:false}),/data-save-flow/);
context.studio.review = null;
assert.match(context.storyFailureMarkup({last_error:'STORY_IMAGE_REFUSED <script>x</script>'}),/ไม่ใช่ปุ่มส่งค้าง/);
assert.doesNotMatch(context.storyFailureMarkup({last_error:'<script>x</script>'}),/<script>/);
assert.equal(context.storyFailureMarkup({}),'');
assert.match(context.storyFailureMarkup({last_error:'STORY_REFERENCE_REQUIRED ขอภาพ'}),/เว็บขอภาพอ้างอิงเพิ่ม ยังไม่ได้สร้างภาพ/);
assert.doesNotMatch(context.storyFailureMarkup({last_error:'STORY_REFERENCE_REQUIRED ขอภาพ'}),/เว็บตอบปฏิเสธภาพแล้ว/);
const responseReview=context.storyFailureMarkup({last_error:'STORY_IMAGE_RESPONSE_REVIEW <img src=x onerror=bad()>'});
assert.match(responseReview,/เว็บตอบข้อความแล้ว แต่ยังไม่พบภาพใหม่ที่ยืนยันได้/);
assert.match(responseReview,/ไม่ส่งซ้ำและไม่เริ่มงานใหม่อัตโนมัติ/);
assert.match(responseReview,/ตรวจคำตอบและผลในแชตเดิมก่อนกดทำต่อ/);
assert.doesNotMatch(responseReview,/<img|<button|data-action|เว็บตอบปฏิเสธภาพแล้ว/);
assert.match(responseReview,/&lt;img/);
console.log('Story content UI: legacy, pending, mismatch, ready, safe text, read-only rendering passed');
